apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: diemkieu/nln_backend:v4
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          #value: jdbc:mysql://mysql-service:3306/mydatabase
          valueFrom:
            configMapKeyRef:
              name: webfood-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          #value: root
          valueFrom:
            configMapKeyRef:
              name: webfood-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          #value: k6030710
          valueFrom:
            secretKeyRef:
              name: webfood-secret
              key: SPRING_DATASOURCE_PASSWORD
        - name: allowedOrigins
          valueFrom:
            configMapKeyRef:
              name: webfood-config
              key: allowedOrigins

 