apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.ports.port }}
      targetPort: {{ .Values.backend.service.ports.targetPort }}
  type: ClusterIP
