apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-deployment
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
      - name: {{ .Release.Name }}-frontend
        image: {{ .Values.frontend.deployment.image }}
        ports:
        - containerPort: {{ .Values.frontend.deployment.ports.containerPort }}
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: REACT_APP_BACKEND_URL
