apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mysql-persistent-storage
spec:
  capacity:
    storage: {{ .Values.mysql.persistentVolume.capacity.storage }}
  accessModes:
    - {{ .Values.mysql.persistentVolume.accessModes }}
  hostPath:
    path: {{ .Values.mysql.persistentVolume.hostPath.path }}