apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pvc
spec:
  accessModes:
    - {{ .Values.mysql.svc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.mysql.svc.resources.requests.storage }}
      